module.exports = {
  common: [
    "@babel/core",
    "@babel/plugin-proposal-class-properties",
    "@babel/plugin-proposal-object-rest-spread",
    "@babel/plugin-transform-for-of",
    "@babel/plugin-transform-runtime",
    "@babel/preset-env",
    "@babel/preset-react",
    "babel-loader",
    "css-loader",
    "file-loader",
  ],
  app: ["@babel/plugin-syntax-dynamic-import", "happypack", "handlebars-loader", "style-loader"],
  lib: ["docz-theme-default", "docz-plugin-css"],
  sass: ["node-sass", "sass-loader"],
  less: ["less", "less-loader"],
  jest: ["jest"],
  eslint: [
    "eslint",
    "babel-eslint",
    "eslint-config-prettier",
    "eslint-plugin-prettier",
    "eslint-plugin-react",
    "precise-commits",
    "prettier",
    "husky",
  ],
};
